spring:
  application:
    name: spring-boot-mybatis-druid
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/transaction_account?useSSL=false&characterEncoding=UTF-8
      username: root
      password: feng1104
      initial-size: 1
      validation-query: SELECT 1
logging:
  level:
    root: DEBUG
  config:
mybatis:
  mapper-locations: classpath:mappers/*.xml
